name: test pytest using docker compose

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Copies the code
        uses: actions/checkout@v4

      - name:
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Run the test
        run: docker compose run test
