name: test pytest using docker compose


on: pull-request
  branches:
    - main


jobs:
  pytest:
  - name: Copies the code 
    uses: actions/checkout@v4
  
  - name: 
  - uses: actions/setup-python@v5
    with:
      python-version: '3.9'
    run:  pip install -r requirements.txt
    
  - name: Run the test
    run: docker compose run test
    