name: Test flask app

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copies code
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: install dependencies
        run: | 
        pip install -r requirements.txt
        

      - name: run app
        run: python test_app.py
